version: '3.8'

services:
  group_9_app:
    image: smdbs/cs553:cs3
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
    env_file: .env
    ports:
      - "12345:7860" 
      - "12346:8000"
      - "12347:9100"  
    networks:
      - monitoring

  group_9_prom:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "12348:9090" 
    networks:
      - monitoring

  group_9_grafana:
    image: grafana/grafana-enterprise
    ports:
      - "12349:3000" 
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Change in production

networks:
  monitoring:
    name: monitoring
    external: true
    
