name: Sync to Hugging Face hub
on:
  workflow_run: 
    workflows: 
      - Python tests
    types:
      - completed

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://smdbs:$HF_TOKEN@huggingface.co/spaces/smdbs/CS553_CaseStudy1 main
